//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Melfa.Robot.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Melfa.Robot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 The system may be abnormal 的當地語系化字串。
        /// </summary>
        internal static string Error_0001_Cause {
            get {
                return ResourceManager.GetString("Error.0001.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 High 的當地語系化字串。
        /// </summary>
        internal static string Error_0001_Level {
            get {
                return ResourceManager.GetString("Error.0001.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Turn the power OFF and ON again. If it comes back, contact your service provider. 的當地語系化字串。
        /// </summary>
        internal static string Error_0001_Measures {
            get {
                return ResourceManager.GetString("Error.0001.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail safe error (SRVOFF) 的當地語系化字串。
        /// </summary>
        internal static string Error_0001_Message {
            get {
                return ResourceManager.GetString("Error.0001.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The system may be abnormal 的當地語系化字串。
        /// </summary>
        internal static string Error_0002_Cause {
            get {
                return ResourceManager.GetString("Error.0002.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 High 的當地語系化字串。
        /// </summary>
        internal static string Error_0002_Level {
            get {
                return ResourceManager.GetString("Error.0002.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Turn the power OFF and ON again. If it comes back, contact your service provider. 的當地語系化字串。
        /// </summary>
        internal static string Error_0002_Measures {
            get {
                return ResourceManager.GetString("Error.0002.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail safe error (STOP) 的當地語系化字串。
        /// </summary>
        internal static string Error_0002_Message {
            get {
                return ResourceManager.GetString("Error.0002.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The problem of the system is the cause 的當地語系化字串。
        /// </summary>
        internal static string Error_0003_Cause {
            get {
                return ResourceManager.GetString("Error.0003.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 High 的當地語系化字串。
        /// </summary>
        internal static string Error_0003_Level {
            get {
                return ResourceManager.GetString("Error.0003.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Turn the power OFF and ON again. If it comes back, contact your service provider. 的當地語系化字串。
        /// </summary>
        internal static string Error_0003_Measures {
            get {
                return ResourceManager.GetString("Error.0003.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The system is abnormal 的當地語系化字串。
        /// </summary>
        internal static string Error_0003_Message {
            get {
                return ResourceManager.GetString("Error.0003.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CPU was not normally treatable 的當地語系化字串。
        /// </summary>
        internal static string Error_0004_Cause {
            get {
                return ResourceManager.GetString("Error.0004.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 High 的當地語系化字串。
        /// </summary>
        internal static string Error_0004_Level {
            get {
                return ResourceManager.GetString("Error.0004.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 It is necessary to change some parts when not improving. If it comes back, contact your service provider.
        ///The &quot;CPU&quot; part in each message varies according to the CPU in which an error is detected.
        ///RCPU_main, CCPU_main, RCPU_sub, CCPU_sub, CPU_main, CPU_sub, FPGA, RCPU_PLD, CCPU_PLD 的當地語系化字串。
        /// </summary>
        internal static string Error_0004_Measures {
            get {
                return ResourceManager.GetString("Error.0004.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CPU watchdog error 的當地語系化字串。
        /// </summary>
        internal static string Error_0004_Message {
            get {
                return ResourceManager.GetString("Error.0004.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The external emergency stop is triggered 的當地語系化字串。
        /// </summary>
        internal static string Error_0050_Cause {
            get {
                return ResourceManager.GetString("Error.0050.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 High 的當地語系化字串。
        /// </summary>
        internal static string Error_0050_Level {
            get {
                return ResourceManager.GetString("Error.0050.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Release the external emergen stop signal 的當地語系化字串。
        /// </summary>
        internal static string Error_0050_Measures {
            get {
                return ResourceManager.GetString("Error.0050.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Emergency Stop (External) 的當地語系化字串。
        /// </summary>
        internal static string Error_0050_Message {
            get {
                return ResourceManager.GetString("Error.0050.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Wiring of the external emergency stop is abnormal 的當地語系化字串。
        /// </summary>
        internal static string Error_0051_Cause {
            get {
                return ResourceManager.GetString("Error.0051.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 High 的當地語系化字串。
        /// </summary>
        internal static string Error_0051_Level {
            get {
                return ResourceManager.GetString("Error.0051.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Turn OFF the power supply.
        ///Confirm whether there is any problem in wiring of the external emergency stop switch.
        ///And, please confirm whether it is wiring of the dual line. Refer to the “Examples of safety measures” given in separate “Standard Specifications Manual” for external emergency stop switch wiring.
        ///Turn on the power supply again after checking. 的當地語系化字串。
        /// </summary>
        internal static string Error_0051_Measures {
            get {
                return ResourceManager.GetString("Error.0051.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 External emergency stop wiring abnormal 的當地語系化字串。
        /// </summary>
        internal static string Error_0051_Message {
            get {
                return ResourceManager.GetString("Error.0051.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The emergency stop line on the operation panel isn&apos;t stable 的當地語系化字串。
        /// </summary>
        internal static string Error_0061_Cause {
            get {
                return ResourceManager.GetString("Error.0061.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 High 的當地語系化字串。
        /// </summary>
        internal static string Error_0061_Level {
            get {
                return ResourceManager.GetString("Error.0061.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm whether there is any problem in wiring of the emergency stop switch on the operation panel.
        ///And, please confirm whether it is wiring of the double line. Refer to the &quot;Examples of safety measures&quot; given in separate &quot;Standard Specifications Manual&quot; for emergency stop switch wiring.
        ///Turn on the power supply again after checking. 的當地語系化字串。
        /// </summary>
        internal static string Error_0061_Measures {
            get {
                return ResourceManager.GetString("Error.0061.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Emergency Stop (Operation Panel) 的當地語系化字串。
        /// </summary>
        internal static string Error_0061_Message {
            get {
                return ResourceManager.GetString("Error.0061.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EMG signal is input. (T.Box) Or when using the UL specification, the brake release switch is turning ON. 的當地語系化字串。
        /// </summary>
        internal static string Error_0070_Cause {
            get {
                return ResourceManager.GetString("Error.0070.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 High 的當地語系化字串。
        /// </summary>
        internal static string Error_0070_Level {
            get {
                return ResourceManager.GetString("Error.0070.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel the T/B emergency stop. Check the emergency stop switch of teaching pendant.. Or when using the UL specification, turn OFF the brake release switch. If the alarm cannot be canceled, check the fuse of the safe unit (TZ348). If the fuse broke off, exchange new fuse. 的當地語系化字串。
        /// </summary>
        internal static string Error_0070_Measures {
            get {
                return ResourceManager.GetString("Error.0070.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Emergency Stop (Teach Box) 的當地語系化字串。
        /// </summary>
        internal static string Error_0070_Message {
            get {
                return ResourceManager.GetString("Error.0070.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The emergency stop signal on the teach box isn&apos;t stable 的當地語系化字串。
        /// </summary>
        internal static string Error_0071_Cause {
            get {
                return ResourceManager.GetString("Error.0071.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 High 的當地語系化字串。
        /// </summary>
        internal static string Error_0071_Level {
            get {
                return ResourceManager.GetString("Error.0071.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm whether there is any problem in wiring of the emergency stop switch on the teach box.
        ///And, please confirm whether it is wiring of the double line. Refer to the &quot;Examples of safety measures&quot; given in separate &quot;Standard Specifications Manual&quot; for external emergency stop switch wiring.
        ///Turn on the power supply again after checking. 的當地語系化字串。
        /// </summary>
        internal static string Error_0071_Measures {
            get {
                return ResourceManager.GetString("Error.0071.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Emergency Stop signal unstable (Teach Box) 的當地語系化字串。
        /// </summary>
        internal static string Error_0071_Message {
            get {
                return ResourceManager.GetString("Error.0071.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Because servo is turned off, the robot can&apos;t move. 的當地語系化字串。
        /// </summary>
        internal static string Error_2000_Cause {
            get {
                return ResourceManager.GetString("Error.2000.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Low 的當地語系化字串。
        /// </summary>
        internal static string Error_2000_Level {
            get {
                return ResourceManager.GetString("Error.2000.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tur the servo ON and then restart. 的當地語系化字串。
        /// </summary>
        internal static string Error_2000_Measures {
            get {
                return ResourceManager.GetString("Error.2000.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The servo is OFF 的當地語系化字串。
        /// </summary>
        internal static string Error_2000_Message {
            get {
                return ResourceManager.GetString("Error.2000.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The start position is outside the operation range. 的當地語系化字串。
        /// </summary>
        internal static string Error_2601_Cause {
            get {
                return ResourceManager.GetString("Error.2601.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Low 的當地語系化字串。
        /// </summary>
        internal static string Error_2601_Level {
            get {
                return ResourceManager.GetString("Error.2601.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Adjust the position 的當地語系化字串。
        /// </summary>
        internal static string Error_2601_Measures {
            get {
                return ResourceManager.GetString("Error.2601.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start position exceeds the limit 的當地語系化字串。
        /// </summary>
        internal static string Error_2601_Message {
            get {
                return ResourceManager.GetString("Error.2601.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The target position is outside the operation range. 的當地語系化字串。
        /// </summary>
        internal static string Error_2602_Cause {
            get {
                return ResourceManager.GetString("Error.2602.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Low 的當地語系化字串。
        /// </summary>
        internal static string Error_2602_Level {
            get {
                return ResourceManager.GetString("Error.2602.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Adjust the position 的當地語系化字串。
        /// </summary>
        internal static string Error_2602_Measures {
            get {
                return ResourceManager.GetString("Error.2602.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Destination position exceeds the limit 的當地語系化字串。
        /// </summary>
        internal static string Error_2602_Message {
            get {
                return ResourceManager.GetString("Error.2602.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The intermediate position is outside the operation range. 的當地語系化字串。
        /// </summary>
        internal static string Error_2603_Cause {
            get {
                return ResourceManager.GetString("Error.2603.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Low 的當地語系化字串。
        /// </summary>
        internal static string Error_2603_Level {
            get {
                return ResourceManager.GetString("Error.2603.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Adjust the position 的當地語系化字串。
        /// </summary>
        internal static string Error_2603_Measures {
            get {
                return ResourceManager.GetString("Error.2603.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Middle position exceeds the limit 的當地語系化字串。
        /// </summary>
        internal static string Error_2603_Message {
            get {
                return ResourceManager.GetString("Error.2603.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This may occur for a position to which the robot cannot reach. 的當地語系化字串。
        /// </summary>
        internal static string Error_2800_Cause {
            get {
                return ResourceManager.GetString("Error.2800.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Low 的當地語系化字串。
        /// </summary>
        internal static string Error_2800_Level {
            get {
                return ResourceManager.GetString("Error.2800.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Adjust the position 的當地語系化字串。
        /// </summary>
        internal static string Error_2800_Measures {
            get {
                return ResourceManager.GetString("Error.2800.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Illegal position data 的當地語系化字串。
        /// </summary>
        internal static string Error_2800_Message {
            get {
                return ResourceManager.GetString("Error.2800.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This may occur for a starting position to which the robot cannot reach. 的當地語系化字串。
        /// </summary>
        internal static string Error_2801_Cause {
            get {
                return ResourceManager.GetString("Error.2801.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Low 的當地語系化字串。
        /// </summary>
        internal static string Error_2801_Level {
            get {
                return ResourceManager.GetString("Error.2801.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Adjust the position 的當地語系化字串。
        /// </summary>
        internal static string Error_2801_Measures {
            get {
                return ResourceManager.GetString("Error.2801.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Illegal start position data 的當地語系化字串。
        /// </summary>
        internal static string Error_2801_Message {
            get {
                return ResourceManager.GetString("Error.2801.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This may occur for a destination position to which the robot cannot reach. 的當地語系化字串。
        /// </summary>
        internal static string Error_2802_Cause {
            get {
                return ResourceManager.GetString("Error.2802.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Low 的當地語系化字串。
        /// </summary>
        internal static string Error_2802_Level {
            get {
                return ResourceManager.GetString("Error.2802.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Adjust the position 的當地語系化字串。
        /// </summary>
        internal static string Error_2802_Measures {
            get {
                return ResourceManager.GetString("Error.2802.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Illegal destination position data 的當地語系化字串。
        /// </summary>
        internal static string Error_2802_Message {
            get {
                return ResourceManager.GetString("Error.2802.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The structure flag of the start point and end point don&apos;t match 的當地語系化字串。
        /// </summary>
        internal static string Error_2810_Cause {
            get {
                return ResourceManager.GetString("Error.2810.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Low 的當地語系化字串。
        /// </summary>
        internal static string Error_2810_Level {
            get {
                return ResourceManager.GetString("Error.2810.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Adjust the position data 的當地語系化字串。
        /// </summary>
        internal static string Error_2810_Measures {
            get {
                return ResourceManager.GetString("Error.2810.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Posture flag is disagree 的當地語系化字串。
        /// </summary>
        internal static string Error_2810_Message {
            get {
                return ResourceManager.GetString("Error.2810.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The designated program was not found 的當地語系化字串。
        /// </summary>
        internal static string Error_4140_Cause {
            get {
                return ResourceManager.GetString("Error.4140.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Low 的當地語系化字串。
        /// </summary>
        internal static string Error_4140_Level {
            get {
                return ResourceManager.GetString("Error.4140.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Designate a different program, or create the designated program. 的當地語系化字串。
        /// </summary>
        internal static string Error_4140_Measure {
            get {
                return ResourceManager.GetString("Error.4140.Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The program was not found 的當地語系化字串。
        /// </summary>
        internal static string Error_4140_Message {
            get {
                return ResourceManager.GetString("Error.4140.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The specified slot is not in the program selection state 的當地語系化字串。
        /// </summary>
        internal static string Error_5120_Cause {
            get {
                return ResourceManager.GetString("Error.5120.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Low 的當地語系化字串。
        /// </summary>
        internal static string Error_5120_Level {
            get {
                return ResourceManager.GetString("Error.5120.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset the program 的當地語系化字串。
        /// </summary>
        internal static string Error_5120_Measure {
            get {
                return ResourceManager.GetString("Error.5120.Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot select program (slot not in program selection state) 的當地語系化字串。
        /// </summary>
        internal static string Error_5120_Message {
            get {
                return ResourceManager.GetString("Error.5120.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot execute during an error 的當地語系化字串。
        /// </summary>
        internal static string Error_5600_Cause {
            get {
                return ResourceManager.GetString("Error.5600.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Low 的當地語系化字串。
        /// </summary>
        internal static string Error_5600_Level {
            get {
                return ResourceManager.GetString("Error.5600.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset the error 的當地語系化字串。
        /// </summary>
        internal static string Error_5600_Measures {
            get {
                return ResourceManager.GetString("Error.5600.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot execute during an error 的當地語系化字串。
        /// </summary>
        internal static string Error_5600_Message {
            get {
                return ResourceManager.GetString("Error.5600.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot execute during stop singal input 的當地語系化字串。
        /// </summary>
        internal static string Error_5610_Cause {
            get {
                return ResourceManager.GetString("Error.5610.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Caution 的當地語系化字串。
        /// </summary>
        internal static string Error_5610_Level {
            get {
                return ResourceManager.GetString("Error.5610.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Turn the stop signal OFF and execute 的當地語系化字串。
        /// </summary>
        internal static string Error_5610_Measures {
            get {
                return ResourceManager.GetString("Error.5610.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot execute during STOP ON 的當地語系化字串。
        /// </summary>
        internal static string Error_5610_Message {
            get {
                return ResourceManager.GetString("Error.5610.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot execute during cycle stop signal input 的當地語系化字串。
        /// </summary>
        internal static string Error_5620_Cause {
            get {
                return ResourceManager.GetString("Error.5620.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Caution 的當地語系化字串。
        /// </summary>
        internal static string Error_5620_Level {
            get {
                return ResourceManager.GetString("Error.5620.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Turn the cycle stop signal OFF 的當地語系化字串。
        /// </summary>
        internal static string Error_5620_Measures {
            get {
                return ResourceManager.GetString("Error.5620.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot execute during CSTOP ON 的當地語系化字串。
        /// </summary>
        internal static string Error_5620_Message {
            get {
                return ResourceManager.GetString("Error.5620.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot execute during servo OFF signal input 的當地語系化字串。
        /// </summary>
        internal static string Error_5630_Cause {
            get {
                return ResourceManager.GetString("Error.5630.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Low 的當地語系化字串。
        /// </summary>
        internal static string Error_5630_Level {
            get {
                return ResourceManager.GetString("Error.5630.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Turn the servo off signal OFF 的當地語系化字串。
        /// </summary>
        internal static string Error_5630_Measures {
            get {
                return ResourceManager.GetString("Error.5630.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot execute during SRVOFF ON 的當地語系化字串。
        /// </summary>
        internal static string Error_5630_Message {
            get {
                return ResourceManager.GetString("Error.5630.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot execute during operation 的當地語系化字串。
        /// </summary>
        internal static string Error_5640_Cause {
            get {
                return ResourceManager.GetString("Error.5640.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Low 的當地語系化字串。
        /// </summary>
        internal static string Error_5640_Level {
            get {
                return ResourceManager.GetString("Error.5640.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Stop the opration, and then execute. 的當地語系化字串。
        /// </summary>
        internal static string Error_5640_Measures {
            get {
                return ResourceManager.GetString("Error.5640.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot execute during RUN 的當地語系化字串。
        /// </summary>
        internal static string Error_5640_Message {
            get {
                return ResourceManager.GetString("Error.5640.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The operation right have not been acquired. 的當地語系化字串。
        /// </summary>
        internal static string Error_6020_Cause {
            get {
                return ResourceManager.GetString("Error.6020.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Low 的當地語系化字串。
        /// </summary>
        internal static string Error_6020_Level {
            get {
                return ResourceManager.GetString("Error.6020.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Acquire the operation rights. 的當地語系化字串。
        /// </summary>
        internal static string Error_6020_Measures {
            get {
                return ResourceManager.GetString("Error.6020.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The operation is disabled 的當地語系化字串。
        /// </summary>
        internal static string Error_6020_Message {
            get {
                return ResourceManager.GetString("Error.6020.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unknown error, check controller troubleshooting manual (BFP-A3480) for more information. 的當地語系化字串。
        /// </summary>
        internal static string Error_Unknown_Cause {
            get {
                return ResourceManager.GetString("Error.Unknown.Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unknown 的當地語系化字串。
        /// </summary>
        internal static string Error_Unknown_Level {
            get {
                return ResourceManager.GetString("Error.Unknown.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unknown error, check controller troubleshooting manual (BFP-A3480) for more information. 的當地語系化字串。
        /// </summary>
        internal static string Error_Unknown_Measures {
            get {
                return ResourceManager.GetString("Error.Unknown.Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unknown error, check controller troubleshooting manual (BFP-A3480) for more information. 的當地語系化字串。
        /// </summary>
        internal static string Error_Unknown_Message {
            get {
                return ResourceManager.GetString("Error.Unknown.Message", resourceCulture);
            }
        }
    }
}
